### ISSUE TITLE
VIP歌曲无法解锁

### ISSUE THREAD

**Issue by wenp5262** [rong6/unlock-music#1]

**Comment by rong6** [comment]
什么平台，我看看
另外我并不是此项目的作者，所以此问题可能无法解决

**Comment by RISES989** [comment]
怎么使用啊

**Comment by max-fmx** [comment]
目前情况是这样：音乐平台都更新了音乐版权加密，原作者也制作了一个重构版，但没有打包成exe，只有网页和应用程序的版本

**Comment by max-fmx** [comment]
> 怎么使用啊

看到html没有，打开它，就是网页，然后跟着他的说明把音乐文件丢进去，你就可以得到破解后的文件

**Comment by max-fmx** [comment]
你可以去试试[重构版](https://git.unlock-music.dev/um/um-react)readme文件中提到的相关项目，终端命令比一个一个点好用多了

**Comment by max-fmx** [comment]
> 

请提供一下你音乐文件加密后的后缀
