### ISSUE TITLE
请尊重原作者

### ISSUE THREAD

**Issue by max-fmx** [rong6/unlock-music#2]
根据MIT协议,您需要标注原作者:[原作者](https://git.unlock-music.dev/um)
参考Unlock Music 项目中的README.md文件提到的:Unlock Music 项目是以学习和技术研究的初衷创建的，修改、再分发时请遵循[授权协议](https://git.unlock-music.dev/um/web/src/branch/master/LICENSE)。

**Comment by rong6** [comment]
你好，我事先并不知情原作者是谁，这个源码是随便从一个网站上找的，我也早已在readme标注我不知道原作者及其Git仓库。稍后我会标记原作者，感谢提醒。

**Comment by YuenSzeHong** [comment]
> 根据MIT协议,您需要标注原作者:[原作者](https://git.unlock-music.dev/um)
> 参考Unlock Music 项目中的README.md文件提到的:Unlock Music 项目是以学习和技术研究的初衷创建的，修改、再分发时请遵循[授权协议](https://git.unlock-music.dev/um/web/src/branch/master/LICENSE)。

所以老哥有新版的预组建吗，现在原作者貌似跑了，官网去不了，也没办法部署新版
